[profile.default]
src = "src"                     # Same source directory as Hardhat
test = "test/foundry"          # Separate directory for Foundry tests to avoid conflicts
out = "artifacts/foundry"      # Output directory for Foundry artifacts
libs = ["node_modules"]        # Add node_modules to find npm dependencies
cache_path = "cache/foundry"   # Separate cache directory
fs_permissions = [{ access = "read", path = "./"}] # Needed for loading env vars

# Fallback on hardhat.config
#solc = "0.8.28"               # Match your Hardhat solidity version
#optimizer = true
#optimizer_runs = 200

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true

[rpc_endpoints]
localhost = "http://localhost:8545"